CREATE TABLE IF NOT EXISTS Patient (
    PatientID SERIAL PRIMARY KEY,
    PatientName VARCHAR(30) NOT NULL,
    Deductible MONEY NOT NULL
);

CREATE TABLE IF NOT EXISTS Doctor (
	DoctorID SERIAL PRIMARY KEY,
	DoctorName varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Appointment (
    DoctorID INT NOT NULL,
    PatientID INT NOT NULL,
    Day DATE NOT NULL,
    IsScheduled BOOLEAN NOT NULL,
    PRIMARY KEY (DoctorID, PatientID, Day),
    FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID) ON DELETE CASCADE,
    FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Visit (
	PatientID INT NOT NULL,
	DoctorID INT NOT NULL,
	Day DATE NOT NULL,
	Diagnosis varchar(500) NOT NULL,
	Treatment varchar(500),
	PRIMARY KEY (PatientID, DoctorID, Day),
	FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE,
	FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MedicalRecord (
	PatientID INT NOT NULL,
	Day DATE NOT NULL,
	Diagnosis varchar(500) NOT NULL,
	Treatment varchar(500),
	PRIMARY KEY (PatientID, Day),
	FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Payment (
	PaymentID SERIAL PRIMARY KEY,
	PatientID INT NOT NULL,
	Amount MONEY NOT NULL,
	FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bill (
	BillID SERIAL PRIMARY KEY,
	PatientID INT NOT NULL,
	Balance MONEY NOT NULL,
	IsPaidByInsurance BOOLEAN NOT NULL,
	FOREIGN KEY (PatientID) REFERENCES Patient(PatientID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BillPayment (
	BillID INT NOT NULL,
	PaymentID INT NOT NULL,
	FOREIGN KEY (BillID) REFERENCES Bill(BillID) ON DELETE CASCADE,
	FOREIGN KEY (PaymentID) REFERENCES Payment(PaymentID) ON DELETE CASCADE
);